SELECT COMMANDS
1.SELECT * FROM Books;
2.SELECT FullName, Email FROM Members;
3.SELECT LoanID, BookID, MemberID, LoanDate FROM Loans;
4.SELECT * FROM Books WHERE Author = 'Paulo Coelho';

SELECT COMMAND USING BETWEEN
1.SELECT Title, YearPublished FROM Books WHERE YearPublished BETWEEN 1990 AND 2010;

SELECT COMMAND USING LIKE
1.SELECT * FROM Members WHERE FullName LIKE 'J%';

SELECT COMMAND USING AND
1.SELECT * FROM Members WHERE JoinDate > '2024-01-01' AND Phone IS NOT NULL;

SELECT COMMAND USING OR
1.SELECT * FROM Books WHERE Author = 'George Orwell' OR Genre = 'Sci-Fic';

SELECT COMMAND USING ORDERBY
1.SELECT * FROM Books ORDER BY Title ASC;
2.SELECT * FROM Members ORDER BY JoinDate DESC;
3.SELECT * FROM Loans ORDER BY ReturnDate IS NULL, ReturnDate ASC;
